### PR TITLE
Hbyu

### PR DESCRIPTION
**Pull request by Aerodiamond**
Ggg

### CODE REVIEW

**Comment by Caceresenzo** [comment]
This work of mine is total garbage. I don't know what i was thinking when I was on this exam...
But this is not a reason to remove it.

**Comment by Caceresenzo** [comment]
If you need a much better version, considere checking out this version:
[Caceresenzo/42/reusable/libft/ft_atoi.c](https://github.com/Caceresenzo/42/blob/master/reusable/libft/ft_atoi.c)

**Comment by Aerodiamond** [comment]
How many grades need to get through the piscine (how many levels)

**Comment by Caceresenzo** [comment]
This is not the place to discuss of this.

But to answer you, there isn't a minimal required level.
As long as you are in the top 140 (i think), you will get pick.

The school doesn't share this kind of information, this is only based on my piscine.

EDIT: Fixed typos

**Comment by Aerodiamond** [comment]
Did you get through the piscine?

**Comment by Caceresenzo** [comment]
Yes

Again, this is not a place to have this kind of conversation.

If you want to ask more question, email me at caceresenzo1502@gmail.com

**Pull request closed without merging**
